grabcut:
  iterations: 5

  gaussian:
    components: 5
    covariance_type: "full"

  energy:
    lambda: 50.0
    beta: 0.5
    gamma: 20.0

  initialization:
    use_gcn_mask: true
    threshold: 0.5
